version: "3.9"
services:
  tws-dependency-mssql:
    container_name: tws-dependency-mssql
    hostname: tws.dependency.mssql
    image: mcr.microsoft.com/azure-sql-edge:1.0.6
    volumes:
      - tws-dependency-mssql-data:/var/opt/mssql
      - tws-dependency-mssql-extensibility-data:/var/opt/mssql-extensibility
      - tws-dependency-mssql-extensibility-data-data:/var/opt/mssql-extensibility/data
      - tws-dependency-mssql-extensibility-log-data:/var/opt/mssql-extensibility/log
    ports:
      - "14330:1433"
    environment:
      - MSSQL_SA_PASSWORD=YourStrong@Passw0rd
      - MSSQL_PID=Developer
      - ACCEPT_EULA=Y

  tws-dependency-rabbitmq:
    container_name: tws-dependency-rabbitmq
    hostname: tws.dependency.rabbitmq
    image: rabbitmq:3.10.5-management
    volumes:
      - tws-dependency-rabbitmq-data:/var/lib/rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

  tws-dependency-redis:
    container_name: tws-dependency-redis
    hostname: tws.dependency.redis
    image: redis:7.0.4
    volumes:
      - "tws-dependency-redis-data:/data"
    ports:
      - "6379:6379"

  tws-dependency-elasticsearch:
    container_name: tws-dependency-elasticsearch
    hostname: tws.dependency.elasticsearch
    image: elasticsearch:7.16.1
    volumes:
      - tws-dependency-elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - discovery.type=single-node

  tws-dependency-kibana:
    container_name: tws-dependency-kibana
    hostname: tws.dependency.kibana
    image: kibana:7.16.1
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=["http://tws.dependency.elasticsearch:9200"]

volumes:
  tws-dependency-mssql-data:
  tws-dependency-mssql-extensibility-data:
  tws-dependency-mssql-extensibility-data-data:
  tws-dependency-mssql-extensibility-log-data:
  tws-dependency-rabbitmq-data:
  tws-dependency-redis-data: 
  tws-dependency-elasticsearch-data:
