version: "3.9"
services:
  tws-identity-server:
    container_name: tws-identity-server
    hostname: tws.identity.server
    build:
      context: .
      dockerfile: ./TeamworkSystem.IdentityServer/Dockerfile
    ports:
      - "5119:80"
      - "7119:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+;http://+
      - ASPNETCORE_HTTPS_PORT=7119
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - ASPNETCORE_Kestrel__Certificates__Default__Password=1234
      - ConnectionStrings__DefaultConnection=Server=tws.dependency.mssql;Database=TeamworkSystemIdentity;User=sa;Password=YourStrong@Passw0rd;
      - EventBusSettings__HostAddress=amqp://guest:guest@tws.dependency.rabbitmq:5672
    depends_on:
      - tws-dependency-mssql
      - tws-dependency-rabbitmq

  tws-identity-api:
    container_name: tws-identity-api
    hostname: tws.identity.api
    build:
      context: .
      dockerfile: ./TeamworkSystem.Identity.API/Dockerfile
    ports:
      - "5137:80"
      - "7137:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+;http://+
      - ASPNETCORE_HTTPS_PORT=7137
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - ASPNETCORE_Kestrel__Certificates__Default__Password=1234
      - ConnectionStrings__DefaultConnection=Server=tws.dependency.mssql;Database=TeamworkSystemIdentity;User=sa;Password=YourStrong@Passw0rd;
      - EventBusSettings__HostAddress=amqp://guest:guest@tws.dependency.rabbitmq:5672
    depends_on:
      - tws-dependency-mssql
      - tws-dependency-rabbitmq

  tws-work-management-api:
    container_name: tws-work-management-api
    hostname: tws.work.management.api
    build:
      context: .
      dockerfile: ./TeamworkSystem.WorkManagement.API/Dockerfile
    ports:
      - "5077:80"
      - "7077:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+;http://+
      - ASPNETCORE_HTTPS_PORT=7077
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - ASPNETCORE_Kestrel__Certificates__Default__Password=1234
      - ConnectionStrings__DefaultConnection=Server=tws.dependency.mssql;Database=TeamworkSystemWorkManagement;User=sa;Password=YourStrong@Passw0rd;
      - EventBusSettings__HostAddress=amqp://guest:guest@tws.dependency.rabbitmq:5672
    depends_on:
      - tws-dependency-mssql
      - tws-dependency-rabbitmq

  tws-social-api:
    container_name: tws-social-api
    hostname: tws.social.api
    build:
      context: .
      dockerfile: ./TeamworkSystem.Social.API/Dockerfile
    ports:
      - "5158:80"
      - "7158:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+;http://+
      - ASPNETCORE_HTTPS_PORT=7158
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - ASPNETCORE_Kestrel__Certificates__Default__Password=1234
      - ConnectionStrings__DefaultConnection=Server=tws.dependency.mssql;Database=TeamworkSystemSocial;User=sa;Password=YourStrong@Passw0rd;
      - EventBusSettings__HostAddress=amqp://guest:guest@tws.dependency.rabbitmq:5672
      - ElasticUrl=http://elasticsearch:9200
    depends_on:
      - tws-dependency-mssql
      - tws-dependency-rabbitmq
      - tws-dependency-elasticsearch
      - tws-dependency-kibana

  tws-content-api:
    container_name: tws-content-api
    hostname: tws.content.api
    build:
      context: .
      dockerfile: ./TeamworkSystem.Content.API/Dockerfile
    ports:
      - "5211:80"
      - "7211:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+;http://+
      - ASPNETCORE_HTTPS_PORT=7211
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - ASPNETCORE_Kestrel__Certificates__Default__Password=1234
      - ConnectionStrings__DefaultConnection=Server=tws.dependency.mssql;Database=TeamworkSystemContent;User=sa;Password=YourStrong@Passw0rd;
      - EventBusSettings__HostAddress=amqp://guest:guest@tws.dependency.rabbitmq:5672
      - CacheSettings__RedisConnectionString=tws.dependency.redis:6379
      - ServicesSettings__WorkManagementUrl=https://tws.work.management.api:443
    depends_on:
      - tws-dependency-mssql
      - tws-dependency-rabbitmq
      - tws-dependency-redis
      - tws-work-management

  tws-gateway:
    container_name: tws-gateway
    hostname: tws.gateway
    build:
      context: .
      dockerfile: ./TeamworkSystem.Gateway/Dockerfile
    ports:
      - "5161:80"
      - "7161:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+;http://+
      - ASPNETCORE_HTTPS_PORT=7161
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - ASPNETCORE_Kestrel__Certificates__Default__Password=1234
    depends_on:
      - tws-identity-api
      - tws-work-management-api
      - tws-content-api

  tws-client:
    container_name: tws-client
    hostname: tws.client
    build:
      context: .
      dockerfile: ./TeamworkSystem.WebClient/Dockerfile
    ports:
      - "8000:80"
      - "8001:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+;http://+
      - ASPNETCORE_HTTPS_PORT=8001
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - ASPNETCORE_Kestrel__Certificates__Default__Password=1234
      - ApiUrl=https://tws.gateway:443
    depends_on:
      - tws-gateway-api
