version: "3.9"
services:
  tws-identity-server:
    container_name: tws-identity-server
    hostname: tws.identity.server
    build:
      context: .
      dockerfile: ./TeamworkSystem.IdentityServer/Dockerfile
    ports:
      - "5119:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+
      - ConnectionStrings__PeopleConnection=Server=host.docker.internal,14330;Database=TeamworkSystemPeople;User=sa;Password=YourStrong@Passw0rd;
      - ConnectionStrings__IdentityServerConfigurationConnection=Server=host.docker.internal,14330;Database=TeamworkSystemConfiguration;User=sa;Password=YourStrong@Passw0rd;
      - ConnectionStrings__IdentityServerOperationalConnection=Server=host.docker.internal,14330;Database=TeamworkSystemOperational;User=sa;Password=YourStrong@Passw0rd;
      - EventBusSettings__HostAddress=amqp://guest:guest@host.docker.internal:5672
      - ElasticUrl=http://host.docker.internal:9200
    depends_on:
      - tws-dependency-mssql
      - tws-dependency-rabbitmq

  tws-identity-api:
    container_name: tws-identity-api
    hostname: tws.identity.api
    build:
      context: .
      dockerfile: ./TeamworkSystem.Identity.API/Dockerfile
    ports:
      - "5137:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+
      - ConnectionStrings__DefaultConnection=Server=host.docker.internal,14330;Database=TeamworkSystemPeople;User=sa;Password=YourStrong@Passw0rd;
      - JwtSecurityKey=SomeVeryRandomSecrityValue
      - EventBusSettings__HostAddress=amqp://guest:guest@host.docker.internal:5672
      - ElasticUrl=http://host.docker.internal:9200
    depends_on:
      - tws-dependency-mssql
      - tws-dependency-rabbitmq

  tws-work-management-api:
    container_name: tws-work-management-api
    hostname: tws.work.management.api
    build:
      context: .
      dockerfile: ./TeamworkSystem.WorkManagement.API/Dockerfile
    ports:
      - "5077:80"
      - "6077:90"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Kestrel__Endpoints__Http__Url=http://*:80
      - Kestrel__Endpoints__GrpcInsecure__Url=http://*:90
      - Kestrel__Endpoints__GrpcInsecure__Protocols=Http2
      - ConnectionStrings__DefaultConnection=Server=host.docker.internal,14330;Database=TeamworkSystemWorkManagement;User=sa;Password=YourStrong@Passw0rd;
      - JwtSecurityKey=SomeVeryRandomSecrityValue
      - EventBusSettings__HostAddress=amqp://guest:guest@host.docker.internal:5672
      - AuthenticationAuthorityUrl=http://host.docker.internal:5119
      - ElasticUrl=http://host.docker.internal:9200
    depends_on:
      - tws-dependency-mssql
      - tws-dependency-rabbitmq

  tws-social-api:
    container_name: tws-social-api
    hostname: tws.social.api
    build:
      context: .
      dockerfile: ./TeamworkSystem.Social.API/Dockerfile
    ports:
      - "5158:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+
      - ConnectionStrings__DefaultConnection=Server=host.docker.internal,14330;Database=TeamworkSystemSocial;User=sa;Password=YourStrong@Passw0rd;
      - JwtSecurityKey=SomeVeryRandomSecrityValue
      - EventBusSettings__HostAddress=amqp://guest:guest@host.docker.internal:5672
      - ElasticUrl=http://host.docker.internal:9200
    depends_on:
      - tws-dependency-mssql
      - tws-dependency-rabbitmq
      - tws-dependency-elasticsearch
      - tws-dependency-kibana

  tws-content-api:
    container_name: tws-content-api
    hostname: tws.content.api
    build:
      context: .
      dockerfile: ./TeamworkSystem.Content.API/Dockerfile
    ports:
      - "5211:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+
      - ConnectionStrings__DefaultConnection=Server=host.docker.internal,14330;Database=TeamworkSystemContent;User=sa;Password=YourStrong@Passw0rd;
      - JwtSecurityKey=SomeVeryRandomSecrityValue
      - EventBusSettings__HostAddress=amqp://guest:guest@host.docker.internal:5672
      - CacheSettings__RedisConnectionString=host.docker.internal:6379
      - ServicesSettings__WorkManagementGrpcUrl=http://tws.work.management.api:90
      - ElasticUrl=http://host.docker.internal:9200
    depends_on:
      - tws-dependency-mssql
      - tws-dependency-rabbitmq
      - tws-dependency-redis
      - tws-work-management-api

  tws-gateway:
    container_name: tws-gateway
    hostname: tws.gateway
    build:
      context: .
      dockerfile: ./TeamworkSystem.Gateway/Dockerfile
    ports:
      - "5161:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+
      - ElasticUrl=http://host.docker.internal:9200
    depends_on:
      - tws-identity-api
      - tws-work-management-api
      - tws-content-api

  tws-client:
    container_name: tws-client
    hostname: tws.client
    build:
      context: .
      dockerfile: ./TeamworkSystem.WebClient/Dockerfile
    ports:
      - "8000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+
      - ApiUrl=http://tws.gateway:80
      - Intermediate__IdentityService=IdentityService/gateway
      - Intermediate__CoreService=CoreService/gateway
      - Intermediate__SocialService=SocialService/gateway
    depends_on:
      - tws-gateway
